# -*- coding:utf-8 -*-
# @Time    : 2017/11/21 16:04
# @Author  : leolee
# @File    : globalList.py
from pygame import *

GLOBAL_MAINSCREEN_LIST = []

GLOBAL_RGB = (0,0,0)
GLOBAL_PENSIZE = 1
#0表示未选，1表示pen,2表示橡皮,3表示喷雾
GLOBAL_PENCHOOSE = 'pen'
GLOBAL_MAINSCREEN = 0
GLOBAL_MAINSCREEN_WIDTH = 0
GLOBAL_MAINSCREEN_HEIGHT = 0

#调色盘
GLOBAL_RED = 0
GLOBAL_GREEN = 0
GLOBAL_BLUE = 0

#pen
GLOBAL_PEN_LASTPOS=(-1,-1)
GLOBAL_PEN_FLAG=False

#spray
GLOBAL_SPRAY_TIME = 0

#rectangle
GLOBAL_RECTANGLE_SCREEN_TMP = Surface((500,500))
GLOBAL_RECTANGLE_START_POS = (-1,-1)